import { FeatureRuleConfig } from '../types';

export const defaultFeaturesList: FeatureRuleConfig[] = [
  {
    id: 'tab_companion',
    nameAr: 'واجهة المحادثة والرفيق',
    nameEn: 'Companion Chat Interface',
    descriptionAr: 'الشاشة الرئيسية للدردشة والتفاعل الذكي مع الرفيق',
    descriptionEn: 'Main companion chat screen and conversational AI',
    category: 'tabs',
    icon: 'MessageCircle',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tab_today',
    nameAr: 'واجهة يومي والمراجعة',
    nameEn: 'Today Agenda & Review Tab',
    descriptionAr: 'جدول اليوم والمهام الحالية والمراجعة اليومية',
    descriptionEn: 'Daily agenda, today tasks, and daily AI review',
    category: 'tabs',
    icon: 'Calendar',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tab_saved',
    nameAr: 'واجهة المحفوظات والمهام',
    nameEn: 'Saved Items & Tasks Tab',
    descriptionAr: 'سجل كافة المهام، المواعيد، الأهداف، والروابط المحفوظة',
    descriptionEn: 'All saved tasks, appointments, goals, and notes repository',
    category: 'tabs',
    icon: 'BookmarkCheck',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tab_profile',
    nameAr: 'واجهة البروفايل والتفضيلات',
    nameEn: 'Profile & Settings Tab',
    descriptionAr: 'إعدادات الحساب، الشخصية، اللغة، وإدارة الاشتراك',
    descriptionEn: 'Account settings, companion personality, language, and plan tier',
    category: 'tabs',
    icon: 'User',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tool_stats',
    nameAr: 'زر ومودال الإحصائيات والاستهلاك',
    nameEn: 'Stats & Analytics Modal',
    descriptionAr: 'إحصائيات إنجاز المهام، استهلاك الذكاء الاصطناعي، ونسب الالتزام',
    descriptionEn: 'Task completion rates, AI token usage, and habit consistency stats',
    category: 'actions',
    icon: 'BarChart3',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
    customLockMessage: 'متاح لجميع المشتركين لاستعراض تقدمهم اليومي والإحصائي',
  },
  {
    id: 'tool_voice_input',
    nameAr: 'زر الإدخال والتسجيل الصوتي',
    nameEn: 'Voice Input / Mic',
    descriptionAr: 'زر الميكروفون للحديث الصوتي المباشر مع الرفيق',
    descriptionEn: 'Direct speech-to-text microphone button in chat',
    category: 'chat_tools',
    icon: 'Mic',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tool_voice_reply',
    nameAr: 'الردود الصوتية للرفيق (TTS)',
    nameEn: 'AI Voice Speech Reply',
    descriptionAr: 'نطق رسائل الرفيق صوتياً بنبرة طبيعية وواقعية',
    descriptionEn: 'Natural text-to-speech audio synthesis responses',
    category: 'chat_tools',
    icon: 'Volume2',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tool_attachments',
    nameAr: 'إرفاق الوسائط والصور والملفات',
    nameEn: 'Media Attachments',
    descriptionAr: 'إمكانية إرسال وتحليل الصور والمستندات داخل الدردشة',
    descriptionEn: 'Image, video and document attachment and vision AI analysis',
    category: 'chat_tools',
    icon: 'Paperclip',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
    customLockMessage: 'ميزة إرفاق الصور والوسائط تتطلب حساباً مفعلاً',
  },
  {
    id: 'tool_private_candid',
    nameAr: 'وضع المصارحة والخواطر السرية الجريئة',
    nameEn: 'Private Candid Thoughts Mode',
    descriptionAr: 'نقاشات صريحة وغير مقيدة وحوارات عميقة مشفرة',
    descriptionEn: 'Unfiltered, confidential, and deep candid conversations',
    category: 'chat_tools',
    icon: 'Flame',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'tool_marital_counseling',
    nameAr: 'مساعد الاستشارات الزوجية والعلاقات',
    nameEn: 'Marital & Relationship Coach',
    descriptionAr: 'جلسات استشارية متخصصة لحل النزاعات وفهم العلاقات',
    descriptionEn: 'Specialized relationship & marriage coaching advisor',
    category: 'chat_tools',
    icon: 'HeartHandshake',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'feature_goals_tracking',
    nameAr: 'تتبع الأهداف والمراحل بالذكاء الاصطناعي',
    nameEn: 'AI Goals & Milestone Tracking',
    descriptionAr: 'تفكيك الأهداف الكبرى إلى مراحل زمنية ومتابعة نسب الإنجاز',
    descriptionEn: 'Strategic goal breakdown, progress bars, and AI milestones analysis',
    category: 'saved_tools',
    icon: 'Target',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'feature_snippet_extractor',
    nameAr: 'استخراج الاقتباسات والملاحظات الطويلة',
    nameEn: 'Long Notes & Snippet Extractor',
    descriptionAr: 'حفظ النصوص الطويلة، الأشعار، والمقتطفات مع استخراج الكبسولات الذكية',
    descriptionEn: 'Long-form note drafting and AI smart snippet extraction',
    category: 'saved_tools',
    icon: 'FileText',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'feature_smart_alarm',
    nameAr: 'المنبه والتذكيرات الصوتية التفاعلية',
    nameEn: 'Smart Interactive Alarms',
    descriptionAr: 'تنبيهات صوتية فورية مع أصوات رنين وتنبيه تفاعلي',
    descriptionEn: 'Full screen ringing alarms and persistent reminder notifications',
    category: 'saved_tools',
    icon: 'Bell',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tool_daily_checkin',
    nameAr: 'رسالة التفقد والاطمئنان اليومي',
    nameEn: 'Daily Wellness Check-in',
    descriptionAr: 'سؤال يومي ذكي لمتابعة المزاج والطاقة ومستوى الإنتاجية',
    descriptionEn: 'Daily proactive prompt to track mood, energy, and habits',
    category: 'chat_tools',
    icon: 'Smile',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'tool_daily_review',
    nameAr: 'توليد ملخص ومراجعة اليوم بالذكاء الاصطناعي',
    nameEn: 'AI Daily Summary Review',
    descriptionAr: 'تقرير مسائي شامل يحلل إنجازات اليوم ونقاط التحسين',
    descriptionEn: 'End-of-day AI comprehensive debrief and performance score',
    category: 'actions',
    icon: 'Sparkles',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'feature_theme_customization',
    nameAr: 'تخصيص الثيمات والوضع الليلي',
    nameEn: 'Theme & Appearance Customizer',
    descriptionAr: 'التبديل بين المظهر الفاتح والداكن والخطوط',
    descriptionEn: 'Dark/Light mode switches and UI styling preferences',
    category: 'preferences',
    icon: 'Palette',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'action_tools_menu',
    nameAr: 'قائمة الخيارات والأدوات السريعة بالهيدر',
    nameEn: 'Header Quick Tools Dropdown',
    descriptionAr: 'زر وقائمة الأدوات السريعة بالهيدر (الوضع الليلي، اللغة، الأذونات)',
    descriptionEn: 'Quick tools dropdown button in header (theme, language, permissions)',
    category: 'actions',
    icon: 'SlidersHorizontal',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'pref_language',
    nameAr: 'محدد وتبديل لغة التطبيق',
    nameEn: 'Language Selector',
    descriptionAr: 'إمكانية تغيير لغة التطبيق من قائمة الأدوات والإعدادات',
    descriptionEn: 'Language switcher in tools menu and settings',
    category: 'preferences',
    icon: 'Globe',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'feature_focus_mode',
    nameAr: 'وضع التركيز (إخفاء شريط التنقل)',
    nameEn: 'Focus Mode (Hide Bottom Nav)',
    descriptionAr: 'إخفاء شريط التنقل السفلي مؤقتاً لتوسيع مساحة المحادثة وزيادة التركيز',
    descriptionEn: 'Temporarily hide bottom navigation bar to maximize conversation display and focus',
    category: 'actions',
    icon: 'Maximize2',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'header_upgrade_button',
    nameAr: 'زر الترقية السريعة بالهيدر (Pro/Upgrade)',
    nameEn: 'Header Pro Upgrade Button',
    descriptionAr: 'التحكم في إظهار أو إخفاء زر الترقية السريعة والتاج في أعلى الهيدر',
    descriptionEn: 'Show or hide the quick Pro upgrade button in the top header',
    category: 'actions',
    icon: 'Crown',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'header_stats_button',
    nameAr: 'زر الإحصائيات بالهيدر (Stats)',
    nameEn: 'Header Stats Button',
    descriptionAr: 'التحكم في إظهار أو إخفاء زر استعراض الإحصائيات في أعلى الهيدر',
    descriptionEn: 'Show or hide the stats analytics trigger button in the top header',
    category: 'actions',
    icon: 'BarChart3',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'action_settings',
    nameAr: 'زر فتح الإعدادات بالهيدر (Settings)',
    nameEn: 'Header Settings Button',
    descriptionAr: 'زر الترس لفتح نافذة الإعدادات الشاملة للتطبيق من أعلى الهيدر',
    descriptionEn: 'Settings gear icon in the top header to access preferences',
    category: 'actions',
    icon: 'SlidersHorizontal',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'consultations_hub',
    nameAr: 'مركز وبوابة الاستشارات المتخصصة',
    nameEn: 'Specialized Consultations Hub',
    descriptionAr: 'بوابة الاستشارات الشاملة (اقتصادية، أسرية، دينية، سياسية، نفسية، زوجية)',
    descriptionEn: 'Hub for specialized advising modes: financial, family, spiritual, political, coaching',
    category: 'chat_tools',
    icon: 'Sparkles',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_financial',
    nameAr: 'استشارة: الاقتصاد والمال والاستثمار',
    nameEn: 'Consultation: Financial & Business',
    descriptionAr: 'مستشار مالي واقتصادي لتحليل الميزانيات، الاستثمار، وخطط الأعمال',
    descriptionEn: 'Specialized financial advisor for budgeting, investing, and enterprise planning',
    category: 'chat_tools',
    icon: 'TrendingUp',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_family',
    nameAr: 'استشارة: الأسرة والتربية والعلاقات',
    nameEn: 'Consultation: Family & Parenting',
    descriptionAr: 'مستشار أسري وتربوي لتوجيه الأبناء وحل الخلافات وتعزيز الترابط العائلي',
    descriptionEn: 'Specialized family counselor for parenting, family harmony, and conflict solving',
    category: 'chat_tools',
    icon: 'Users',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_religious',
    nameAr: 'استشارة: الفقه والدين والتزكية الروحية',
    nameEn: 'Consultation: Spiritual & Religious',
    descriptionAr: 'توجيهات فقهية وروحية معتدلة تعزز السكينة والطمأنينة والأخلاق',
    descriptionEn: 'Balanced Islamic jurisprudence, spiritual tranquility, and ethical guidance',
    category: 'chat_tools',
    icon: 'BookOpen',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_political',
    nameAr: 'استشارة: التحليل السياسي والاستراتيجي',
    nameEn: 'Consultation: Geopolitics & Strategy',
    descriptionAr: 'تحليل موضوعي للأحداث الدولية والعلاقات الاستراتيجية والسياسات العامة',
    descriptionEn: 'Objective geopolitical analysis, policy briefing, and strategic assessments',
    category: 'chat_tools',
    icon: 'Compass',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_psychological',
    nameAr: 'استشارة: الصحة النفسية وتطوير الذات',
    nameEn: 'Consultation: Psychology & Life Coaching',
    descriptionAr: 'إرشاد نفسي وتطوير العادات، التغلب على الاحتراق النفسي، وبناء الإنتاجية',
    descriptionEn: 'Life coaching, emotional resilience, stress management, and personal growth',
    category: 'chat_tools',
    icon: 'Sparkles',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'consultation_marital',
    nameAr: 'استشارة: الدعم الزوجي والعلاقة الحميمة (18+)',
    nameEn: 'Consultation: Marital Intimacy Support (18+)',
    descriptionAr: 'جلسة استشارية متخصصة ومقننة للزوجين وذوي الاحتياجات الخاصة (18+)',
    descriptionEn: 'Specialized 18+ verified marital intimacy counseling and guidance session',
    category: 'chat_tools',
    icon: 'HeartHandshake',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'badge_lock',
  },
  {
    id: 'button_admin_panel',
    nameAr: 'زر الدخول للوحة التحكم الإدارية (Admin)',
    nameEn: 'Admin Panel Access Button',
    descriptionAr: 'التحكم في ظهور أو إخفاء زر الانتقال للوحة التحكم الإدارية في الإعدادات وقائمة الأدوات',
    descriptionEn: 'Control visibility of the Admin Panel portal trigger in Settings and tools menu',
    category: 'actions',
    icon: 'ShieldAlert',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'header_upgrade_button',
    nameAr: 'زر الترقية والاشتراك (Upgrade / Pro)',
    nameEn: 'Header Upgrade & Pro Button',
    descriptionAr: 'زر الترقية السريع إلى الخطط المدفوعة الظاهر في الترويسة العلوية، يتيح التحكم بالظهور أو الإخفاء أو تخصيص الخطط والمستخدمين',
    descriptionEn: 'Header quick upgrade button with flexible audience, plans, and visibility control',
    category: 'actions',
    icon: 'Crown',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
  {
    id: 'header_quick_tools_button',
    nameAr: 'زر الأدوات السريعة بالهيدر',
    nameEn: 'Header Quick Tools Button',
    descriptionAr: 'زر فتح القائمة المنسدلة للأدوات والتفضيلات السريعة في الشريط العلوي',
    descriptionEn: 'Quick tools launcher dropdown button in the top navigation bar',
    category: 'actions',
    icon: 'SlidersHorizontal',
    targetAudience: 'everyone',
    specificUsers: [],
    allowedPlans: ['all'],
    progressiveDisclosure: { enabled: false, minAccountAgeDays: 0, minMessagesSent: 0, minCompletedTasks: 0 },
    timeWindow: { enabled: false },
    lockedBehavior: 'hide',
  },
];
